keys:
  - &hosts:
    - &cayley age1d4wjzrr7rkw2nlllezslj57ht4ns2fltlrm2mesp3lunr74dh53qwde3mp
    - &sophie age1mej7uzyt4h46r4uvyh0hwdq04034uk0n57nmeg6slu8gaql78gqs4jegal
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
        - *cayley
        - *sophie
