keys:
  - &hosts:
    - &cayley age1ejf4y50ccls8ulspz9t5cqz8mjm600f50q3kx4e7tj5kw33a65aq4m2znj
    - &sophie age1mej7uzyt4h46r4uvyh0hwdq04034uk0n57nmeg6slu8gaql78gqs4jegal
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
        - *cayley
        - *sophie
